export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

import Providers from "./providers"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
